### ISSUE TITLE
Change the default state 

### ISSUE THREAD

**Issue by surya0180** [WAD-Team-Alpha/Hospital_Review_System#49]
At many sections like, search bars, registeration pages etc, the default state is selected as andhra pradesh, [@surya0180 @prathyush11 @sekharsa @satyamsingh-sg @bannu0snake ] everyone should fix this issue if it is present in your respective feature

**Comment by surya0180** [comment]
I think this @sekharsa @prathyush11 should fix this issue because they are handling the searchbar feature. The default option is helpful only in the search bars.

**Comment by prathyush11** [comment]
I have fixed for my part

**Comment by surya0180** [comment]
Thanks @prathyush11 @sekharsa for solving this issue
